
# docker-compose.ymlの書き方は下記を参照する
# https://docs.docker.jp/index.html

version: "3.8"

services:
  
  # WEBサーバ
  web:
    image: httpd:latest
    restart: always
    volumes:
      - ./webapp:/webapp
    ports:
      - "10080:80"
    depends_on:
      - db
  
  # DBサーバ
  db:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD: mysql_root_paswsword
      - MYSQL_PORT: 3306
    ports:
      - 13306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
  
  # PHPmyadminサーバ
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_ARBITRARY: 1
      - PMA_HOST: db
      - PMA_PORT: 3306
      - PMA_USER: root
      - PMA_PASSWORD: mysql_root_paswsword
    ports:
      - 10081:80
    depends_on:
      - db


