
# docker-compose.ymlの書き方は下記を参照する
# https://docs.docker.com/compose/compose-file/

version: "3.8"

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_paswsword
      MYSQL_PORT: 3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
  web:
    image: httpd:latest
    restart: always
    volumes:
      - ./webapp:/webapp
    ports:
      - "8080:80"
    depends_on:
      - db

