
# docker-compose.ymlの書き方は下記を参照する
# https://docs.docker.com/compose/compose-file/

version: "3.8"

services:
  
  web:
    image: httpd:latest
    restart: always
    volumes:
      - ./webapp:/webapp
    ports:
      - "20080:80"
    depends_on:
      - db
  
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_paswsword
      MYSQL_PORT: 3306
    ports:
      - 23306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
  
  


